src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_deleted;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_bestseller;

    /**
     * @ORM\Column(type="integer")
     */
    private $publishing_year;

    /**
     * @ORM\Column(type="integer")
     */
    private $created;

    /**
     * @ORM\Column(type="string")
     */
    private $isbn;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $excerpt;

    /**
     * @ORM\ManyToMany(targetEntity=Author::class, inversedBy="books")
     */
    private $authors;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="books")
     */
    private $categories;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cover;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIsDeleted(): ?bool
    {
        return $this->is_deleted;
    }

    public function setIsDeleted(bool $is_deleted): self
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

    public function getIsBestSellerIcon(): ?string
    {
        return $this->is_bestseller
            ? '<i class="bi bi-check bi-4x" style="font-size: 30px"></i>'
            : '<i class="bi bi-x bi-4x" style="font-size: 30px"></i>';
    }

    public function getIsBestSeller(): ?bool
    {
        return $this->is_bestseller;
    }

    public function setIsBestSeller(bool $is_bestseller): self
    {
        $this->is_bestseller = $is_bestseller;

        return $this;
    }

    public function getPublishingYear(): ?int
    {
        return $this->publishing_year;
    }

    public function setPublishingYear(int $publishing_year): self
    {
        $this->publishing_year = $publishing_year;

        return $this;
    }

    public function getCreated(): ?int {
        return $this->created;
    }

    public function getCreatedDate(): ?string {
        return date('Y-m-d H:i:s', $this->created);
    }

    public function setCreated($created): self {
        $this->created = $created;

        return $this;
    }

    public function getIsbn(): ?string {
        return $this->isbn;
    }

    public function setIsbn($isbn): self {
        $this->isbn = $isbn;

        return $this;
    }

    public function getDescription(): ?string {
        return $this->description;
    }

    public function setDescription($description): self {
        $this->description = $description;

        return $this;
    }

    public function getExcerpt(): ?string {
        return $this->excerpt;
    }

    public function setExcerpt($excerpt): self {
        $this->excerpt = $excerpt;

        return $this;
    }

    /**
     * @return Collection<int, Author>
     */
    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function setAuthors($authors): self
    {
        $this->authors = $authors;
        return $this;
    }

    public function addAuthor(Author $author): self
    {
        if (!$this->authors->contains($author)) {
            $this->authors[] = $author;
        }

        return $this;
    }

    public function removeAuthor(Author $author): self
    {
        $this->authors->removeElement($author);

        return $this;
    }

    public function getAuthorsWithDescription(): array {
        $authors = [];
        foreach ($this->getAuthors() as $author) {
            $authors[] = ['name' => $author->getFullName(), 'description' => $author->getInfo()];
        }
        return $authors;
    }
    /**
     * @return string
     */
    public function getAuthorNames(): ?string {
        $authors = $this->getAuthors();
        $result = '';
        foreach ($authors as $author) {
            $result .= $author->getFullName() . ', ';
        }
        return rtrim($result, ', ');
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function setCategories($categories): self
    {
        $this->categories = $categories;
        return $this;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getCategoryNames(): ?string {
        $categories = $this->getCategories();
        $result = '';
        foreach ($categories as $category) {
            $result .= $category->getName() . ', ';
        }
        return rtrim($result, ', ');
    }

    public function getCategoryWithSimilarBooks(BookRepository $bookRepository): array {
        $categories = [];
        foreach ($this->getCategories() as $category) {
            $bookNames = [];
            foreach ($bookRepository->findByCategory($category->getId(), $this->getId()) as $book) {
                $bookNames[] = $book->getName();
            }
            $categories[$category->getName()] = $bookNames;
        }
        return $categories;
    }

    public function uploadFile(UploadedFile $file, SluggerInterface $slugger, string $dirName): ?string {
        $newFilename = null;
        if ($file) {
            $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = $slugger->slug($originalFilename);
            $newFilename = $safeFilename.'-'.uniqid().'.'.$file->guessExtension();
            $file->move(
                $dirName,
                $newFilename
            );

        }
        return $newFilename;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(?string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getDataShort(): array {
        $authors = [];
        foreach ($this->getAuthors() as $author) {
            $authors[] = $author->getDataShort();
        }
        $categories = [];
        foreach ($this->getCategories() as $category) {
            $categories[] = $category->getDataShort();
        }
        return [
            'id' => $this->getId(),
            'name' => $this->getName(),
            'authors' => $authors,
            'categories' => $categories,
            'publishing_year' => $this->getPublishingYear(),
            'isbn' => $this->getIsbn(),
            'created_date' => $this->getCreatedDate(),
            'is_bestseller' => $this->getIsBestSeller(),
        ];
    }

    public function getDataFull(BookRepository $bookRepository): array {
        $authors = [];
        foreach ($this->getAuthors() as $author) {
            $authors[] = $author->getDataShort();
        }
        $categories = [];
        foreach ($this->getCategories() as $category) {
            $categories[] = $category->getDataShort();
        }
        return [
            'id' => $this->getId(),
            'name' => $this->getName(),
            'authors' => $authors,
            'categories' => $categories,
            'similar_books' => $this->getCategoryWithSimilarBooks($bookRepository),
            'is_deleted' => $this->getIsDeleted(),
            'publishing_year' => $this->getPublishingYear(),
            'is_bestseller' => $this->getIsBestSeller(),
            'created_date' => $this->getCreatedDate(),
            'isbn' => $this->getIsbn(),
            'description' => $this->getDescription(),
            'excerpt' => $this->getExcerpt(),
            'cover' => $this->getCover(),
        ];
    }
}

src/Controller/Library/AbstractApiController.php
<?php

namespace App\Controller\Library;

use App\Entity\Book;
use App\Repository\BookRepository;
use FOS\RestBundle\Controller\AbstractFOSRestController;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

abstract class AbstractApiController extends AbstractFOSRestController
{
    protected function buildForm(string $type, $data = null, array $options = []): FormInterface
    {
        $options = array_merge($options, [
            'csrf_protection' => false,
        ]);
        return $this->container->get('form.factory')->createNamed('', $type, $data, $options);
    }

    protected function respond($data, int $statusCode = Response::HTTP_OK): Response
    {
        return $this->handleView($this->view($data, $statusCode));
    }
}

src/Controller/Library/AuthorApiController.php
<?php

namespace App\Controller\Library;

use App\Entity\Author;
use App\Repository\AuthorRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class AuthorApiController extends AbstractApiController
{
    private AuthorRepository $authorRepository;

    public function __construct(AuthorRepository $authorRepository)
    {
        $this->authorRepository = $authorRepository;
    }

    /**
     * @Route("/api/get_authors", methods={"GET"}, name="get_authors")
     */
    public function getAuthors(Request $request): Response
    {
        return $this->respond($this->authorRepository->getAuthorList());
    }

    /**
     * @Route("/api/get_author/{id}", methods={"GET"}, name="get_author")
     */
    public function getAuthor(Request $request, Author $author): Response
    {
        return $this->respond($author->getDataFull());
    }
}

src/Controller/Library/BookApiController.php
<?php

namespace App\Controller\Library;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\AuthorRepository;
use App\Repository\BookRepository;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class BookApiController extends AbstractApiController
{
    private BookRepository $bookRepository;
    private AuthorRepository $authorRepository;
    private CategoryRepository $categoryRepository;
    private SluggerInterface $slugger;

    public function __construct(
        BookRepository $bookRepository,
        AuthorRepository $authorRepository,
        CategoryRepository $categoryRepository,
        SluggerInterface $slugger
    )
    {
        $this->bookRepository = $bookRepository;
        $this->authorRepository = $authorRepository;
        $this->categoryRepository = $categoryRepository;
        $this->slugger = $slugger;
    }

    /**
     * @Route("/api/get_books", methods={"GET"}, name="get_books")
     */
    public function getBooks(Request $request): Response
    {
        return $this->respond($this->bookRepository->getBookList());
    }

    /**
     * @Route("/api/get_book/{id}", methods={"GET"}, name="get_book")
     */
    public function getBook(Request $request, Book $book): Response
    {
        if ($book->getIsDeleted()) {
            return $this->respond(['error' => 'This book is deleted'], 403);
        }
        return $this->respond($book->getDataFull($this->bookRepository));
    }

    /**
     * @Route("/api/create_book", methods={"POST"}, name="create_book")
     */
    public function createBook(Request $request): Response
    {
        $authors = $this->authorRepository->getAuthorsForSelect();
        $categories = $this->categoryRepository->getCategoriesForSelect();
        $form = $this->buildForm(
        BookType::class,
            null,
            ['authors' => $authors, 'categories' => $categories]
        );
        $form->handleRequest($request);
        if (!$form->isSubmitted() || !$form->isValid()) {
            return $this->respond($form, Response::HTTP_BAD_REQUEST);
        }
        $book = $form->getData();
        if ($categoryIds = $form->get('categories')->getData()) {
           $book->setCategories($this->categoryRepository->findBy(['id' => $categoryIds]));
        }
        if ($authorIds = $form->get('authors')->getData()) {
            $book->setAuthors($this->authorRepository->findBy(['id' => $authorIds]));
        }
        $book->setCreated(time());
        $this->getDoctrine()->getManager()->persist($book);
        $this->getDoctrine()->getManager()->flush();
        return $this->respond($book->getDataFull($this->bookRepository));
    }

    /**
     * @Route("/api/update_book/{id}", methods={"PATCH"}, name="update_book")
     */
    public function updateBook(Request $request, Book $book): Response
    {
        $authors = $this->authorRepository->getAuthorsForSelect();
        $categories = $this->categoryRepository->getCategoriesForSelect();
        $form = $this->buildForm(
            BookType::class,
            $book,
            [
                'authors' => $authors,
                'categories' => $categories,
                'method' => $request->getMethod()
            ]
        );
        $form->handleRequest($request);
        if (!$form->isSubmitted() || !$form->isValid()) {
            return $this->respond($form, Response::HTTP_BAD_REQUEST);
        }
        $book = $form->getData();
        if ($categoryIds = $form->get('categories')->getData()) {
            $book->setCategories($this->categoryRepository->findBy(['id' => $categoryIds]));
        }
        if ($authorIds = $form->get('authors')->getData()) {
            $book->setAuthors($this->authorRepository->findBy(['id' => $authorIds]));
        }
        $this->getDoctrine()->getManager()->persist($book);
        $this->getDoctrine()->getManager()->flush();
        return $this->respond($book->getDataFull($this->bookRepository));
    }

    /**
     * @Route("/api/delete_book/{id}", methods={"DELETE"}, name="delete_book")
     */
    public function deleteBook(Request $request, Book $book): Response
    {
        if (!$book || $book->getIsDeleted()) {
            return $this->respond(['error' => 'Book not found'], 404);
        }

        $em = $this->getDoctrine()->getManager();
        $book->setIsDeleted(true);
        $em->persist($book);
        $em->flush();
        return $this->respond(['message' => 'success']);
    }
}

src/Controller/Library/CategoryApiController.php
<?php

namespace App\Controller\Library;

use App\Repository\CategoryRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategoryApiController extends AbstractApiController
{
    private CategoryRepository $categoryRepository;

    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * @Route("/api/get_categories", methods={"GET"}, name="get_categories")
     */
    public function getCategories(Request $request): Response
    {
        return $this->respond($this->categoryRepository->getCategoryList());
    }
}

templates/library/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{ form_label(form.name) }}
        {{ form_widget(form.name, {'attr':{'class':'form-control'}}) }}
        {{ form_errors(form.name) }}
    </div>
    <div class="form-group">
        {{ form_label(form.description) }}
        {{ form_widget(form.description, {'attr':{'class':'form-control'}}) }}
        {{ form_errors(form.description) }}
    </div>
    <div class="form-group">
        {{ form_label(form.isbn) }}
        {{ form_widget(form.isbn, {'attr':{'class':'form-control'}}) }}
        {{ form_errors(form.isbn) }}
    </div>
    <div class="form-group">
        {{ form_label(form.excerpt) }}
        {{ form_widget(form.excerpt, {'attr':{'class':'form-control'}}) }}
        {{ form_errors(form.excerpt) }}
    </div>
    <div class="form-group">
        {{ form_label(form.publishing_year) }}
        {{ form_widget(form.publishing_year, {'attr':{'class':'form-control'}}) }}
        {{ form_errors(form.publishing_year) }}
    </div>
    <div class="form-group">
        {{ form_label(form.categories) }}
        {{ form_widget(form.categories, {'attr':{'class':'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_label(form.authors) }}
        {{ form_widget(form.authors, {'attr':{'class':'form-control'}}) }}
    </div>
    <br>
    <div class="form-group">
        {% if cover is defined and cover|length %}
            <img class="img-thumbnail" src="{{ asset('uploads/covers/' ~ cover) }}" alt="book cover">
        {% endif %}
        {{ form_widget(form.cover) }}
    </div>
    {{ form_label(form.is_deleted) }}
    {{ form_widget(form.is_deleted) }}
    {{ form_label(form.is_bestseller) }}
    {{ form_widget(form.is_bestseller) }}
    <div class="form-group">
        <button class="btn btn-info mt-2 text-white">Submit</button>
        {% if id is defined and id|length %}
            <a href="{{ path('book_delete_completely',{'id': id }) }}" style="margin-top: 8px" onclick="return confirm('do you want to delete this book completely?')" class="btn btn-danger"><i class="bi bi-trash"></i></a>
        {% endif %}
        <a href="{{ path('app_library') }}" style="margin-top: 8px" class="btn btn-success">Back to library</a>
    </div>
{{ form_end(form) }}

templates/library/create.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h3 class="mt-5 mb-5">Create Book</h3>
                {% for message in app.flashes('error') %}
                    <div class="alert alert-danger">
                        {{ message }}
                    </div>
                {% endfor %}
                {{ include('library/_form.html.twig') }}
            </div>
        </div>
    </div>

{% endblock %}

templates/library/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">
        <div class="row">
            {% for message in app.flashes('notice') %}
                <div class="alert alert-success mt-4 mb-6">
                    {{ message }}
                </div>
            {% endfor %}

            <nav class="navbar navbar-light bg-light">
                <div class="form-group inline">
                    <a href="{{ path('book_create') }}" class="btn pull-left btn-success">Add</a>
                    <a target="_blank" href="{{ path('get_books') }}" class="btn btn-outline-success pull-left my-2 my-sm-0">Api book list</a>
                    <a target="_blank" href="{{ path('get_book',{'id': 1 }) }}" class="btn btn-outline-success pull-left my-2 my-sm-0">Api get book</a>
                </div>
            </nav>

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Authors</th>
                    <th scope="col">Categories</th>
                    <th scope="col">Publishing Year</th>
                    <th scope="col">ISBN</th>
                    <th scope="col">Added to library</th>
                    <th scope="col">Bestseller</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for item in data %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.authorNames }}</td>
                        <td>{{ item.categoryNames }}</td>
                        <td>{{ item.publishingYear }}</td>
                        <td>{{ item.isbn }}</td>
                        <td>{{ item.createdDate }}</td>
                        <td>{{ item.isBestsellerIcon|raw }}</td>
                        <td>
                            <a href="{{ path('book_show',{'id': item.id }) }}" class="btn btn-success"><i class="bi bi-eye"></i></a><br>
                            <a href="{{ path('book_update',{'id': item.id }) }}" class="btn btn-warning"><i class="bi bi-pencil"></i></a><br>
                            <a href="{{ path('book_delete',{'id': item.id }) }}" onclick="return confirm('are you sure?')" class="btn btn-danger"><i class="bi bi-trash"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/library/show.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">
        <td class="row">
            <h3 class="mt-5 mb-5">{{ book.name }}</h3>
            <table class="table">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ book.id }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ book.name }}</td>
                </tr>
                <tr>
                    <th>Authors</th>
                    <td>
                        {% for author in authors %}
                            <p>{{ author|raw }}</p>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Categories</th>
                    <td>
                        {% for category, similarBooks in categories %}
                            <p> * <b>{{ category }}</b>.
                            {% if similarBooks|length %}
                                Other books in this category:</p>
                                <p>{{ similarBooks }}</p>
                            {% else %}
                                </p>
                            {% endif %}
                            <br>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Deleted</th>
                    <td>{{ book.isDeleted ? 'Yes' : 'No' }}</td>
                </tr>
                <tr>
                    <th>Publishing year</th>
                    <td>{{ book.publishingYear }}</td>
                </tr>
                <tr>
                    <th>bestseller</th>
                    <td>{{ book.isBestseller ? 'Yes' : 'No' }}</td>
                </tr>
                <tr>
                    <th>Created</th>
                    <td>{{ book.createdDate }}</td>
                </tr>
                <tr>
                    <th>Isbn</th>
                    <td>{{ book.isbn }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ book.description }}</td>
                </tr>
                <tr>
                    <th>Excerpt</th>
                    <td>{{ book.excerpt }}</td>
                </tr>
                <tr>
                    <th>cover</th>
                    <td>
                        {% if book.cover|length %}
                            <img class="img-thumbnail" src="{{ asset('uploads/covers/' ~ book.cover) }}" alt="book cover"></td>
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a href="{{ path('app_library') }}" style="margin-top: 8px" class="btn btn-success">Back to library</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/library/update.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h3 class="mt-5 mb-5">Update Book</h3>
                {% for message in app.flashes('error') %}
                    <div class="alert alert-danger">
                        {{ message }}
                    </div>
                {% endfor %}
                {{ include('library/_form.html.twig') }}
            </div>
        </div>
    </div>

{% endblock %}